# Databricks notebook source
# COMMAND ----------

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.SQL_TRANSFORM_DUMMY_TARGET(DUPLICATE_ROW_CNT STRING,
SQL_TRANSFORM_ERROR STRING,
ABORT_SESSION STRING) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_HTL_EARNED_PRE(EARN_DAY_DT DATE,
LOCATION_ID INT,
WEEK_DT DATE,
OVERNIGHT_KITTY_GUEST_CNT INT,
OVERNIGHT_DOG_GUEST_CNT INT,
OVERNIGHT_TOTAL_GUEST_CNT INT,
DAY_CAMP_PLAYROOM_CNT INT,
DAY_CARE_CNT INT,
OVERNIGHT_WITH_DDC_CNT INT,
TOTAL_DAYCAMP_CNT INT,
TOTAL_GUEST_CNT INT,
NIGHT_PETCARE_SPECIALIST_HRS INT,
FRONT_DESK_HRS INT,
BACK_OF_HOUSE_HRS INT,
SUPERVISOR_HRS INT,
PLAYROOM_HRS INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_HTL_PLAYROOM_CAPACITY(LOCATION_ID INT,
DAY_OF_WEEK STRING,
PLAYROOM_CAP_EFF_DT DATE,
PLAYROOM_CAP_END_DT DATE,
STORE_NBR INT,
NORMAL_HRS_ROOM_QTY INT,
PLAYROOM_01_CAPACITY INT,
PLAYROOM_02_CAPACITY INT,
PLAYROOM_03_CAPACITY INT,
PLAYROOM_04_CAPACITY INT,
PLAYROOM_05_CAPACITY INT,
PLAYROOM_06_CAPACITY INT,
PLAYROOM_07_CAPACITY INT,
PLAYROOM_08_CAPACITY INT,
PLAYROOM_09_CAPACITY INT,
PLAYROOM_10_CAPACITY INT,
LOAD_TSTMP TIMESTAMP) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_HTL_VARIABLES(STORE_NBR INT,
DEFAULT_STORE_FLAG STRING,
PS2_HTL_VAR_REC_EFF_DT DATE,
PS2_HTL_VAR_REC_END_DT DATE,
TY_WEIGHT_PCNT INT,
LY_WEIGHT_PCNT INT,
FRONT_DESK_FIXED_HRS INT,
FRONT_DESK_VAR_HRS INT,
PLAYROOM_VAR_HRS INT,
BACK_OF_HOUSE_FIXED_HRS INT,
BACK_OF_HOUSE_VAR_HRS INT,
OVERNIGHT_TRESHHOLD INT,
OVERNIGHT_UPPER_VALUE INT,
OVERNIGHT_LOWER_VALUE INT,
SUPERVISOR_HRS INT,
LOAD_TSTMP TIMESTAMP) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_HTL_EARNED(EARN_DAY_DT DATE,
LOCATION_ID INT,
STORE_NBR INT,
WEEK_DT DATE,
FISCAL_WK INT,
FISCAL_MO INT,
FISCAL_YR INT,
OVERNIGHT_KITTY_GUEST_CNT INT,
OVERNIGHT_DOG_GUEST_CNT INT,
OVERNIGHT_TOTAL_GUEST_CNT INT,
DAY_CAMP_PLAYROOM_CNT INT,
DAY_CARE_CNT INT,
OVERNIGHT_WITH_DDC_CNT INT,
TOTAL_DAYCAMP_CNT INT,
TOTAL_GUEST_CNT INT,
NIGHT_PETCARE_SPECIALIST_HRS INT,
FRONT_DESK_HRS INT,
BACK_OF_HOUSE_HRS INT,
SUPERVISOR_HRS INT,
PLAYROOM_HRS INT,
TOTAL_EARNED_HRS INT,
AVG_WAGE_RATE INT,
TOTAL_EARNED_AMT INT,
UPDATE_TSTMP TIMESTAMP,
LOAD_TSTMP TIMESTAMP) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_HTL_ETL_CONTROL(PS2_HTL_PROCESS_ID INT,
PS2_HTL_PROCESS_DESC STRING,
PS2_HTL_RUN_DT DATE,
UPDATE_TSTMP TIMESTAMP) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_NEW_STORE_PRE(WEEK_DT DATE,
LOCATION_ID INT,
STORE_NBR INT,
SFT_OPEN_DT DATE,
PLAN_SALES_AMT INT,
ACTUAL_SALES_AMT INT,
CUSTOM_AD_HOC_HRS INT,
GRAND_OPENING_HRS INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_NEW_STORE_EARNED(WEEK_DT DATE,
LOCATION_ID INT,
STORE_NBR INT,
SFT_OPEN_DT DATE,
WEEK_STORE_OPENED INT,
PLAN_SALES_AMT INT,
ACTUAL_SALES_AMT INT,
MATRIX_HRS INT,
CUSTOM_AD_HOC_HRS INT,
GRAND_OPENING_HRS INT,
EARNED_HRS INT,
LOAD_TSTMP TIMESTAMP) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_C_EARN_WAGE_PRE(WEEK_DT TIMESTAMP,
LOCATION_ID INT,
TTL_EARNED_HRS INT,
WFA_SAL_MGR_HRS INT,
ACT_SAL_MGR_HRS INT,
ACT_SAL_MGR_AMT INT,
CNT_OF_HRLY_MGRS INT,
AVG_ACT_WAGE_RATE INT,
HOLIDAY_OT_HRS INT,
STR_HRLY_MGR_AVG_WG_RT INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_CA_C_EARN_WAGE_PRE(WEEK_DT TIMESTAMP,
LOCATION_ID INT,
TTL_EARNED_HRS INT,
WFA_SAL_MGR_HRS INT,
ACT_SAL_MGR_HRS INT,
ACT_SAL_MGR_AMT INT,
CNT_OF_HRLY_MGRS INT,
AVG_ACT_WAGE_RATE INT,
STR_HRLY_MGR_AVG_WG_RT INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_CORE_HOLIDAY_LKUP(DAY_DT DATE,
DEFAULT_STORE_FLAG STRING,
LOCATION_ID INT,
OT_TYPE STRING,
COUNTRY_CD STRING,
STORE_NBR STRING) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_CA_C_EARN_PRE(WEEK_DT TIMESTAMP,
LOCATION_ID INT,
WEIGHTED_AVG_WAGE_RATE INT,
ACT_SAL_MGR_AMT INT,
EARNED_OT_HRS INT,
EARNED_OT_AMT INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.SQL_TRANSFORM_DUMMY_TARGET(DUPLICATE_ROW_CNT STRING,
SQL_TRANSFORM_ERROR STRING,
ABORT_SESSION STRING) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_BLUE_LAW_STORE_LKUP(LOCATION_ID INT,
EFF_DT DATE,
END_DT DATE,
STORE_NBR INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_C_EARN_PRE(WEEK_DT TIMESTAMP,
LOCATION_ID INT,
WEIGHTED_AVG_WAGE_RATE INT,
ACT_SAL_MGR_AMT INT,
EARNED_OT_HRS INT,
EARNED_OT_AMT INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_CORE_OT_PRE(WEEK_DT DATE,
LOCATION_ID INT,
OVER_TIME_HRS INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_HTL_EARN_WAGE_PRE(WEEK_DT TIMESTAMP,
LOCATION_ID INT,
STORE_NBR INT,
BUSINESS_TYPE STRING,
ADJUSTED_AMT INT,
ADJUSTED_HRS INT,
ACTUAL_AMT INT,
ACTUAL_HRS INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_CA_HTL_EARN_HRS_PRE(WEEK_DT TIMESTAMP,
PAY_WEEK_DT TIMESTAMP,
LOCATION_ID INT,
STATE_CD STRING,
BUSINESS_TYPE STRING,
TTL_HOTEL_SALES_AMT INT,
EARNED_HRS INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_CA_HTL_EARN_WAGE_PRE(PAY_WEEK_DT TIMESTAMP,
LOCATION_ID INT,
STORE_NBR INT,
BUSINESS_TYPE STRING,
TTL_HRS INT,
TTL_AMT INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_HTL_EARN_HRS_PRE(WEEK_DT TIMESTAMP,
LOCATION_ID INT,
STATE_CD STRING,
BUSINESS_TYPE STRING,
TTL_HOTEL_SALES_AMT INT,
EARNED_HRS INT,
EXCH_RATE INT) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.PS2_EARNED_LABOR(WEEK_DT TIMESTAMP,
LOCATION_ID INT,
WFA_BUSN_AREA_ID INT,
WFA_DEPT_ID INT,
WFA_TASK_ID INT,
TYPE STRING,
SOURCE STRING,
EARNED_OT_HRS INT,
EARNED_LOC_OT_AMT INT,
EARNED_TTL_HRS INT,
EARNED_LOC_TTL_AMT INT,
ACTUAL_EXCH_RATE INT,
FISCAL_WK INT,
FISCAL_MO INT,
FISCAL_YR INT,
STORE_NBR INT,
WFA_BUSN_AREA_DESC STRING,
WFA_DEPT_DESC STRING,
WFA_TASK_DESC STRING,
LOAD_DT TIMESTAMP) USING DELTA;