# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")

# COMMAND ----------
%run ./MappingUtility

# COMMAND ----------
mainWorkflowId = dbutils.widgets.get("mainWorkflowId")
mainWorkflowRunId = dbutils.widgets.get("mainWorkflowRunId")
parentName = dbutils.widgets.get("parentName")
preVariableAssignment = dbutils.widgets.get("preVariableAssignment")
postVariableAssignment = dbutils.widgets.get("postVariableAssignment")
truncTargetTableOptions = dbutils.widgets.get("truncTargetTableOptions")
variablesTableName = dbutils.widgets.get("variablesTableName")

# COMMAND ----------
#Truncate Target Tables
truncateTargetTables(truncTargetTableOptions)

# COMMAND ----------
#Pre presession variable updation
updateVariable(preVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_ps2_htl_variables")

# COMMAND ----------
fetchAndCreateVariables(parentName,"m_ps2_htl_variables", variablesTableName, mainWorkflowId)

# COMMAND ----------
# DBTITLE 1, Shortcut_to_UDH_PS2_HTL_VARIABLES_0


query_0 = f"""SELECT
  STORE_NBR AS STORE_NBR,
  DEFAULT_STORE_FLAG AS DEFAULT_STORE_FLAG,
  PS2_HTL_VAR_REC_EFF_DT AS PS2_HTL_VAR_REC_EFF_DT,
  PS2_HTL_VAR_REC_END_DT AS PS2_HTL_VAR_REC_END_DT,
  TY_WEIGHT_PCNT AS TY_WEIGHT_PCNT,
  LY_WEIGHT_PCNT AS LY_WEIGHT_PCNT,
  FRONT_DESK_FIXED_HRS AS FRONT_DESK_FIXED_HRS,
  FRONT_DESK_VAR_HRS AS FRONT_DESK_VAR_HRS,
  PLAYROOM_VAR_HRS AS PLAYROOM_VAR_HRS,
  BACK_OF_HOUSE_FIXED_HRS AS BACK_OF_HOUSE_FIXED_HRS,
  BACK_OF_HOUSE_VAR_HRS AS BACK_OF_HOUSE_VAR_HRS,
  OVERNIGHT_TRESHHOLD AS OVERNIGHT_TRESHHOLD,
  OVERNIGHT_UPPER_VALUE AS OVERNIGHT_UPPER_VALUE,
  OVERNIGHT_LOWER_VALUE AS OVERNIGHT_LOWER_VALUE,
  SUPERVISOR_HRS AS SUPERVISOR_HRS,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  UDH_PS2_HTL_VARIABLES"""

df_0 = spark.sql(query_0)

df_0.createOrReplaceTempView("Shortcut_to_UDH_PS2_HTL_VARIABLES_0")

# COMMAND ----------
# DBTITLE 1, SQ_Shortcut_to_UDH_PS2_HTL_VARIABLES_1


query_1 = f"""SELECT
  STORE_NBR AS STORE_NBR,
  DEFAULT_STORE_FLAG AS DEFAULT_STORE_FLAG,
  PS2_HTL_VAR_REC_EFF_DT AS PS2_HTL_VAR_REC_EFF_DT,
  PS2_HTL_VAR_REC_END_DT AS PS2_HTL_VAR_REC_END_DT,
  TY_WEIGHT_PCNT AS TY_WEIGHT_PCNT,
  LY_WEIGHT_PCNT AS LY_WEIGHT_PCNT,
  FRONT_DESK_FIXED_HRS AS GSA_FIXED_HRS,
  FRONT_DESK_VAR_HRS AS GSA_VAR_HRS,
  PLAYROOM_VAR_HRS AS PLAYROOM_VAR_HRS,
  BACK_OF_HOUSE_FIXED_HRS AS BACK_OF_HOUSE_FIXED_HRS,
  BACK_OF_HOUSE_VAR_HRS AS BACK_OF_HOUSE_VAR_HRS,
  OVERNIGHT_TRESHHOLD AS OVERNIGHT_TRESHHOLD,
  OVERNIGHT_UPPER_VALUE AS OVERNIGHT_UPPER_VALUE,
  OVERNIGHT_LOWER_VALUE AS OVERNIGHT_LOWER_VALUE,
  SUPERVISOR_HRS AS SUPERVISOR_HRS,
  LOAD_TSTMP AS LOAD_TSTMP,
  monotonically_increasing_id() AS Monotonically_Increasing_Id
FROM
  Shortcut_to_UDH_PS2_HTL_VARIABLES_0"""

df_1 = spark.sql(query_1)

df_1.createOrReplaceTempView("SQ_Shortcut_to_UDH_PS2_HTL_VARIABLES_1")

# COMMAND ----------
# DBTITLE 1, EXP_CheckChanges_2


query_2 = f"""SELECT
  STORE_NBR AS STORE_NBR,
  DEFAULT_STORE_FLAG AS DEFAULT_STORE_FLAG,
  PS2_HTL_VAR_REC_EFF_DT AS PS2_HTL_VAR_REC_EFF_DT,
  PS2_HTL_VAR_REC_END_DT AS PS2_HTL_VAR_REC_END_DT,
  IFF(
    ISNULL(PS2_HTL_VAR_REC_END_DT),
    TO_DATE('20991231', 'YYYYMMDD'),
    PS2_HTL_VAR_REC_END_DT
  ) AS PS2_HTL_VAR_REC_END_DT_NN,
  TY_WEIGHT_PCNT AS TY_WEIGHT_PCNT,
  LY_WEIGHT_PCNT AS LY_WEIGHT_PCNT,
  GSA_FIXED_HRS AS GSA_FIXED_HRS,
  GSA_VAR_HRS AS GSA_VAR_HRS,
  PLAYROOM_VAR_HRS AS PLAYROOM_VAR_HRS,
  BACK_OF_HOUSE_FIXED_HRS AS BACK_OF_HOUSE_FIXED_HRS,
  BACK_OF_HOUSE_VAR_HRS AS BACK_OF_HOUSE_VAR_HRS,
  OVERNIGHT_TRESHHOLD AS OVERNIGHT_TRESHHOLD,
  OVERNIGHT_UPPER_VALUE AS OVERNIGHT_UPPER_VALUE,
  OVERNIGHT_LOWER_VALUE AS OVERNIGHT_LOWER_VALUE,
  SUPERVISOR_HRS AS SUPERVISOR_HRS,
  LOAD_TSTMP AS LOAD_TSTMP,
  Monotonically_Increasing_Id AS Monotonically_Increasing_Id
FROM
  SQ_Shortcut_to_UDH_PS2_HTL_VARIABLES_1"""

df_2 = spark.sql(query_2)

df_2.createOrReplaceTempView("EXP_CheckChanges_2")

# COMMAND ----------
# DBTITLE 1, PS2_HTL_VARIABLES


spark.sql("""INSERT INTO
  PS2_HTL_VARIABLES
SELECT
  STORE_NBR AS STORE_NBR,
  DEFAULT_STORE_FLAG AS DEFAULT_STORE_FLAG,
  PS2_HTL_VAR_REC_EFF_DT AS PS2_HTL_VAR_REC_EFF_DT,
  PS2_HTL_VAR_REC_END_DT_NN AS PS2_HTL_VAR_REC_END_DT,
  TY_WEIGHT_PCNT AS TY_WEIGHT_PCNT,
  LY_WEIGHT_PCNT AS LY_WEIGHT_PCNT,
  GSA_FIXED_HRS AS FRONT_DESK_FIXED_HRS,
  GSA_VAR_HRS AS FRONT_DESK_VAR_HRS,
  PLAYROOM_VAR_HRS AS PLAYROOM_VAR_HRS,
  BACK_OF_HOUSE_FIXED_HRS AS BACK_OF_HOUSE_FIXED_HRS,
  BACK_OF_HOUSE_VAR_HRS AS BACK_OF_HOUSE_VAR_HRS,
  OVERNIGHT_TRESHHOLD AS OVERNIGHT_TRESHHOLD,
  OVERNIGHT_UPPER_VALUE AS OVERNIGHT_UPPER_VALUE,
  OVERNIGHT_LOWER_VALUE AS OVERNIGHT_LOWER_VALUE,
  SUPERVISOR_HRS AS SUPERVISOR_HRS,
  LOAD_TSTMP AS LOAD_TSTMP
FROM
  EXP_CheckChanges_2""")

# COMMAND ----------
#Post session variable updation
updateVariable(postVariableAssignment, variablesTableName, mainWorkflowId, parentName, "m_ps2_htl_variables")

# COMMAND ----------
#Update Mapping Variables in database.
persistVariables(variablesTableName, "m_ps2_htl_variables", mainWorkflowId, parentName)
