# Databricks notebook source
# COMMAND ----------

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.WFA_TIME_SHEET_PUNCH(DAY_DT TIMESTAMP,
WEEK_DT TIMESTAMP,
TIME_SHEET_ITEM_ID INT,
STRT_DTM TIMESTAMP,
END_DTM TIMESTAMP,
LOCATION_ID INT,
EMPLOYEE_ID BIGINT,
WFA_BUSN_AREA_ID INT,
WFA_BUSN_AREA_DESC STRING,
WFA_DEPT_ID INT,
WFA_DEPT_DESC STRING,
WFA_TASK_ID INT,
WFA_TASK_DESC STRING,
UPDATE_DT TIMESTAMP,
LOAD_DT TIMESTAMP) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.WFA_TIME_SHEET_PUNCH_PRE(DAY_DT TIMESTAMP,
TIME_SHEET_ITEM_ID INT,
STRT_DTM TIMESTAMP,
END_DTM TIMESTAMP,
STORE_NBR INT,
EMPLOYEE_ID BIGINT,
WFA_BUSN_AREA_DESC STRING,
WFA_DEPT_DESC STRING,
WFA_TASK_DESC STRING,
LOAD_DT TIMESTAMP) USING DELTA;